from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parent.parent


@dataclass(frozen=True)
class PiecePreset:
    slug: str
    title: str
    midi_path: Path
    preferred_tracks: tuple[int, ...]
    default_player: str
    launch_delay: float
    light_delay: float
    note: str


PIECES = {
    "cavalleria_rusticana": PiecePreset(
        slug="cavalleria_rusticana",
        title="Cavalleria rusticana (Intermezzo)",
        midi_path=REPO_ROOT / "midi" / "cavalleria_rusticana_intermezzo.mid",
        preferred_tracks=(1,),
        default_player="timidity",
        launch_delay=0.0,
        light_delay=0.1,
        note="Kunst der Fuge piano-roll sequence of the Intermezzo. The light score follows the single note-bearing track.",
    ),
    "chopin_prelude_e_minor": PiecePreset(
        slug="chopin_prelude_e_minor",
        title="Chopin Prelude in E minor",
        midi_path=REPO_ROOT / "midi" / "chopin_prelude_op28_no4_e_minor.mid",
        preferred_tracks=(1,),
        default_player="timidity",
        launch_delay=0.0,
        light_delay=0.1,
        note="BitMidi piano sequence of Prelude Op. 28 No. 4. The light score follows the single note-bearing piano track.",
    ),
    "clair_de_lune": PiecePreset(
        slug="clair_de_lune",
        title="Clair de lune",
        midi_path=REPO_ROOT / "midi" / "clair_de_lune.mid",
        preferred_tracks=(1, 2),
        default_player="timidity",
        launch_delay=0.0,
        light_delay=0.1,
        note="Mutopia piano score export. The light score follows both staves so the upper and lower motion stay present in the four-lane reduction.",
    ),
    "gymnopedie_no_1": PiecePreset(
        slug="gymnopedie_no_1",
        title="Gymnopedie No. 1",
        midi_path=REPO_ROOT / "midi" / "gymnopedie_no_1.mid",
        preferred_tracks=(1, 2),
        default_player="timidity",
        launch_delay=0.0,
        light_delay=0.1,
        note="Mutopia piano score export. The light score follows both staves so the treble line and bass pulse stay together.",
    ),
    "o_mio_babbino_caro": PiecePreset(
        slug="o_mio_babbino_caro",
        title="O mio babbino caro",
        midi_path=REPO_ROOT / "midi" / "o_mio_babbino_caro_violin.mid",
        preferred_tracks=(1, 2),
        default_player="timidity",
        launch_delay=0.0,
        light_delay=0.1,
        note="BitMidi arrangement revoiced to Violin. The light score follows both note-bearing tracks, and the default playback path uses the TiMidity++ CLI synth.",
    ),
    "pavane_pour_une_infante_defunte": PiecePreset(
        slug="pavane_pour_une_infante_defunte",
        title="Pavane pour une infante defunte",
        midi_path=REPO_ROOT / "midi" / "pavane_pour_une_infante_defunte.mid",
        preferred_tracks=(1,),
        default_player="timidity",
        launch_delay=0.0,
        light_delay=0.1,
        note="Kunst der Fuge piano sequence by K. Oguri. The light score follows the single note-bearing piano track.",
    ),
    "nessun_dorma": PiecePreset(
        slug="nessun_dorma",
        title="Nessun dorma",
        midi_path=REPO_ROOT / "midi" / "nessun_dorma.mid",
        preferred_tracks=(1, 2, 3),
        default_player="timidity",
        launch_delay=0.0,
        light_delay=0.1,
        note="FluteTunes flute-and-piano arrangement from Turandot. The light score follows the melody and both piano staves so the aria line and harmonic weight stay together.",
    ),
    "vissi_darte": PiecePreset(
        slug="vissi_darte",
        title="Vissi d'arte",
        midi_path=REPO_ROOT / "midi" / "vissi_darte.mid",
        preferred_tracks=(16,),
        default_player="timidity",
        launch_delay=0.0,
        light_delay=0.1,
        note="BitMidi orchestral sequence from Tosca. The light score follows the Tosca vocal track so the four-lane reduction stays focused on the aria line.",
    ),
    "e_lucevan_le_stelle": PiecePreset(
        slug="e_lucevan_le_stelle",
        title="E lucevan le stelle",
        midi_path=REPO_ROOT / "midi" / "e_lucevan_le_stelle.mid",
        preferred_tracks=(1, 2, 3),
        default_player="timidity",
        launch_delay=0.0,
        light_delay=0.1,
        note="FluteTunes flute-and-piano arrangement from Tosca. The light score follows the melody and both piano staves so the vocal contour and accompaniment stay present together.",
    ),
    "dirty_work": PiecePreset(
        slug="dirty_work",
        title="Dirty Work",
        midi_path=REPO_ROOT / "midi" / "dirty_work.mid",
        preferred_tracks=(1, 5, 6, 8),
        default_player="timidity",
        launch_delay=0.0,
        light_delay=0.1,
        note="MidiWorld sequence of Steely Dan's Dirty Work. The light score follows the lead line, keyboard parts, and bass so the groove and vocal contour stay readable.",
    ),
    "ventura_highway": PiecePreset(
        slug="ventura_highway",
        title="Ventura Highway",
        midi_path=REPO_ROOT / "midi" / "ventura_highway.mid",
        preferred_tracks=(6, 7, 9, 10),
        default_player="timidity",
        launch_delay=0.0,
        light_delay=0.1,
        note="MidiWorld sequence of America's Ventura Highway. The light score follows the lead hook, bass, and core guitar strums for a clear soft-rock pulse.",
    ),
    "sailing": PiecePreset(
        slug="sailing",
        title="Sailing",
        midi_path=REPO_ROOT / "midi" / "sailing.mid",
        preferred_tracks=(1, 2, 3, 4),
        default_player="timidity",
        launch_delay=0.0,
        light_delay=0.1,
        note="MidiWorld sequence of Christopher Cross's Sailing. The light score follows melody, bass, piano, and guitar so the arrangement stays smooth without overloading the lane reducer.",
    ),
    "brandy_youre_a_fine_girl": PiecePreset(
        slug="brandy_youre_a_fine_girl",
        title="Brandy (You're a Fine Girl)",
        midi_path=REPO_ROOT / "midi" / "brandy_youre_a_fine_girl.mid",
        preferred_tracks=(1, 2, 3),
        default_player="timidity",
        launch_delay=0.0,
        light_delay=0.1,
        note="MidiWorld sequence of Looking Glass's Brandy. The light score follows the main keyboard reduction, bass, and lead brass line.",
    ),
    "escape_the_pina_colada_song": PiecePreset(
        slug="escape_the_pina_colada_song",
        title="Escape (The Pina Colada Song)",
        midi_path=REPO_ROOT / "midi" / "escape_the_pina_colada_song.mid",
        preferred_tracks=(2, 3, 4),
        default_player="timidity",
        launch_delay=0.0,
        light_delay=0.1,
        note="MidiWorld sequence of Rupert Holmes's Escape. The light score follows bass, rhythm, and the vocal line for a clean three-layer reduction.",
    ),
    "summer_breeze": PiecePreset(
        slug="summer_breeze",
        title="Summer Breeze",
        midi_path=REPO_ROOT / "midi" / "summer_breeze.mid",
        preferred_tracks=(1, 2, 4, 5),
        default_player="timidity",
        launch_delay=0.0,
        light_delay=0.1,
        note="MidiWorld sequence of Seals and Crofts's Summer Breeze. The light score follows bass, keys, guitar, and flute lead to keep the texture airy but legible.",
    ),
    "how_deep_is_your_love": PiecePreset(
        slug="how_deep_is_your_love",
        title="How Deep Is Your Love",
        midi_path=REPO_ROOT / "midi" / "how_deep_is_your_love.mid",
        preferred_tracks=(1, 2, 5),
        default_player="timidity",
        launch_delay=0.0,
        light_delay=0.1,
        note="MidiWorld sequence of the Bee Gees' How Deep Is Your Love. The light score follows piano, bass, and the lead melody line.",
    ),
    "year_of_the_cat": PiecePreset(
        slug="year_of_the_cat",
        title="Year of the Cat",
        midi_path=REPO_ROOT / "midi" / "year_of_the_cat.mid",
        preferred_tracks=(3, 4, 6, 10),
        default_player="timidity",
        launch_delay=0.0,
        light_delay=0.1,
        note="MidiWorld sequence of Al Stewart's Year of the Cat. The light score follows piano, bass, flute, and sax to capture the arrangement's melodic landmarks.",
    ),
    "aint_no_mountain_high_enough": PiecePreset(
        slug="aint_no_mountain_high_enough",
        title="Ain't No Mountain High Enough",
        midi_path=REPO_ROOT / "midi" / "aint_no_mountain_high_enough.mid",
        preferred_tracks=(0,),
        default_player="timidity",
        launch_delay=0.0,
        light_delay=0.1,
        note="MidiWorld sequence credited to The Supremes. This source is a merged full-arrangement track, so the light score follows the single note-bearing track.",
    ),
    "stand_by_me": PiecePreset(
        slug="stand_by_me",
        title="Stand By Me",
        midi_path=REPO_ROOT / "midi" / "stand_by_me.mid",
        preferred_tracks=(4, 8, 9),
        default_player="timidity",
        launch_delay=0.0,
        light_delay=0.1,
        note="MidiWorld sequence of Ben E. King's Stand By Me. The light score follows the bass line and the two strongest melodic/harmonic tracks.",
    ),
    "dock_of_the_bay": PiecePreset(
        slug="dock_of_the_bay",
        title="(Sittin' On) The Dock of the Bay",
        midi_path=REPO_ROOT / "midi" / "dock_of_the_bay.mid",
        preferred_tracks=(1, 2),
        default_player="timidity",
        launch_delay=0.0,
        light_delay=0.1,
        note="BitMidi reduction of Otis Redding's Dock of the Bay. The light score follows both piano-style tracks in the source.",
    ),
    "what_a_difference_a_day_makes": PiecePreset(
        slug="what_a_difference_a_day_makes",
        title="What a Difference a Day Makes",
        midi_path=REPO_ROOT / "midi" / "what_a_difference_a_day_makes.mid",
        preferred_tracks=(1, 2, 4),
        default_player="timidity",
        launch_delay=0.0,
        light_delay=0.1,
        note="BitMidi sequence of What a Difference a Day Makes. The light score follows melody, fretless bass, and electric piano for a cleaner standard-pop reduction.",
    ),
}
